import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { Chatbot } from "@/components/ui/chatbot";
import { NotificationBanner } from "@/components/notification-banner";

export const metadata: Metadata = {
  title: 'McDonald',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3547507951048319"
          crossOrigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <amp-auto-ads type="adsense"
          data-ad-client="ca-pub-3547507951048319">
        </amp-auto-ads>
        <NotificationBanner />
        {children}
        <Toaster />
        <Chatbot />
      </body>
    </html>
  );
}
